name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-lastest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      
    - run: npm run test
      env:
        CI: true
     
